import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Input } from "@/components/ui/input";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const roboto = Roboto({
  variable: "--font-roboto-thin",
  subsets: ["vietnamese"],
  weight: ["100", "300"],
});

export const metadata: Metadata = {
  title: "Engineering, Construction, Procurement & Project management",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.variable}>
        <header>
          <div className="z-[999] bg-white p-4 fixed shadow-2xs left-0 right-0 flex justify-end">
            <div className="flex gap-[16px] items-center">
              <ul className="flex gap-5 text-white">
                <li>
                  <Link href={"/"} className="text-black">Trang chủ</Link>
                </li>
                <li>
                  <Link href={"/"} className="text-black">Giới thiệu</Link>
                </li>
                <li>
                  <Link href={"/"} className="text-black">Năng lực thi công</Link>
                </li>
                <li>
                  <Link href={"/du-an"} className="text-black">Dự án</Link>
                </li>
                <li>
                  <Link href={"/"} className="text-black">Tin tức</Link>
                </li>
                <li>
                  <Link href={"/"} className="text-black">Tuyển dụng</Link>
                </li>
              </ul>
              <Input placeholder="Search ..." className="w-[200px] bg-white" />
            </div>
          </div>
        </header>
        <div className="h-[80px]" />
        {children}
      </body>
    </html>
  );
}
